"""
TrustField - Database Models
SQLAlchemy ORM models for all persistent entities.
"""

import enum
from datetime import datetime
from typing import List, Optional

from sqlalchemy import (
    Boolean, Column, DateTime, Enum, Float, ForeignKey,
    Integer, JSON, String, Text, ARRAY,
)
from sqlalchemy.orm import relationship

from db.database import Base
from sqlalchemy.orm import relationship, backref


# ─── Enums ────────────────────────────────────────────────────────────────────

class AlertSeverity(str, enum.Enum):
    CRITICAL = "critical"
    HIGH = "high"
    MEDIUM = "medium"
    LOW = "low"


class AlertStatus(str, enum.Enum):
    OPEN = "open"
    IN_PROGRESS = "in_progress"
    RESOLVED = "resolved"
    DISMISSED = "dismissed"


class ContainmentStatus(str, enum.Enum):
    PENDING = "pending"
    IN_PROGRESS = "in_progress"
    COMPLETED = "completed"
    FAILED = "failed"
    CANCELLED = "cancelled"


class ScanStatus(str, enum.Enum):
    PENDING = "pending"
    RUNNING = "running"
    COMPLETED = "completed"
    FAILED = "failed"
    CANCELLED = "cancelled"


class UserRole(str, enum.Enum):
    VIEWER = "viewer"
    ANALYST = "analyst"
    ADMIN = "admin"


# ─── Models ───────────────────────────────────────────────────────────────────

class User(Base):
    """Platform user with role-based access control."""
    __tablename__ = "users"

    id = Column(Integer, primary_key=True, index=True)
    email = Column(String(255), unique=True, nullable=False, index=True)
    username = Column(String(100), unique=True, nullable=False)
    hashed_password = Column(String(255), nullable=False)
    full_name = Column(String(255))
    role = Column(Enum(UserRole), default=UserRole.VIEWER, nullable=False)
    is_active = Column(Boolean, default=True, nullable=False)
    created_at = Column(DateTime, default=datetime.utcnow, nullable=False)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)
    last_login = Column(DateTime)

    # Relationships
    initiated_actions = relationship(
        "ContainmentAction", foreign_keys="ContainmentAction.initiated_by", back_populates="initiator"
    )
    resolved_alerts = relationship(
        "Alert", foreign_keys="Alert.resolved_by", back_populates="resolver"
    )
    scan_jobs = relationship("ScanJob", back_populates="initiator")


class Alert(Base):
    """Security alert generated by detection engines or ML anomaly detection."""
    __tablename__ = "alerts"

    id = Column(Integer, primary_key=True, index=True)
    title = Column(String(500), nullable=False)
    description = Column(Text)
    severity = Column(Enum(AlertSeverity), nullable=False, index=True)
    status = Column(Enum(AlertStatus), default=AlertStatus.OPEN, nullable=False, index=True)

    # Cloud context
    cloud_provider = Column(String(50), index=True)     # aws | azure | gcp | k8s
    account_id = Column(String(255))                    # AWS account / Azure subscription
    region = Column(String(100))
    resource_id = Column(String(500), index=True)       # ARN, object ID, etc.
    resource_type = Column(String(100))                 # IAM user, role, SP, etc.

    # Detection metadata
    alert_type = Column(String(100), index=True)        # PRIVILEGE_ESCALATION, ANOMALY, etc.
    risk_score = Column(Float, default=0.0)
    confidence = Column(Float, default=0.0)
    detection_source = Column(String(100))              # rule_engine | ml_isolation_forest | gnn
    raw_evidence = Column(JSON)                         # Supporting data from detector
    path_id = Column(String(32), index=True)            # Dedup key from EscalationPath.path_id

    # Graph context
    source_node_id = Column(String(255))
    target_node_id = Column(String(255))
    escalation_path = Column(JSON)                      # List of node IDs forming the path
    
    # Analyst workflow
    analyst_notes = Column(Text)
    assigned_to = Column(Integer, ForeignKey("users.id"), nullable=True)
    resolved_by = Column(Integer, ForeignKey("users.id"), nullable=True)
    resolved_at = Column(DateTime)

    # Timestamps
    created_at = Column(DateTime, default=datetime.utcnow, nullable=False, index=True)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)

    # Relationships
    resolver = relationship("User", foreign_keys=[resolved_by], back_populates="resolved_alerts")
    containment_actions = relationship("ContainmentAction", back_populates="alert")


class ContainmentAction(Base):
    """Records of automated or manual containment actions."""
    __tablename__ = "containment_actions"

    id = Column(Integer, primary_key=True, index=True)
    alert_id = Column(Integer, ForeignKey("alerts.id"), nullable=True, index=True)
    parent_action_id = Column(Integer, ForeignKey("containment_actions.id"), nullable=True)

    action_type = Column(String(100), nullable=False)   # REVOKE_CREDENTIALS, DISABLE_ACCOUNT, etc.
    cloud_provider = Column(String(50), nullable=False)
    target_resource = Column(String(500), nullable=False)

    status = Column(Enum(ContainmentStatus), default=ContainmentStatus.PENDING, nullable=False, index=True)
    result = Column(Text)                               # JSON result from the engine
    error_message = Column(Text)

    initiated_by = Column(Integer, ForeignKey("users.id"), nullable=False)

    created_at = Column(DateTime, default=datetime.utcnow, nullable=False)
    started_at = Column(DateTime)
    completed_at = Column(DateTime)

    # Relationships
    alert = relationship("Alert", back_populates="containment_actions")
    initiator = relationship("User", foreign_keys=[initiated_by], back_populates="initiated_actions")
    rollback_actions = relationship(
    "ContainmentAction",
    foreign_keys=[parent_action_id],
    backref=backref("parent_action", remote_side=[id]),
)


class ScanJob(Base):
    """Tracks cloud IAM scan jobs and their progress."""
    __tablename__ = "scan_jobs"

    id = Column(String(36), primary_key=True)           # UUID
    status = Column(Enum(ScanStatus), default=ScanStatus.PENDING, nullable=False, index=True)

    providers_requested = Column(JSON)                  # ["aws", "azure", "gcp", "k8s"]
    providers_scanned = Column(JSON)                    # Successfully scanned providers

    # Results
    nodes_discovered = Column(Integer, default=0)
    edges_discovered = Column(Integer, default=0)
    alerts_generated = Column(Integer, default=0)
    error_message = Column(Text)

    initiated_by = Column(Integer, ForeignKey("users.id"), nullable=False)

    created_at = Column(DateTime, default=datetime.utcnow, nullable=False, index=True)
    started_at = Column(DateTime)
    completed_at = Column(DateTime)

    # Relationships
    initiator = relationship("User", back_populates="scan_jobs")


class AuditLog(Base):
    """Immutable audit trail for all sensitive platform actions."""
    __tablename__ = "audit_logs"

    id = Column(Integer, primary_key=True, index=True)
    user_id = Column(Integer, ForeignKey("users.id"), nullable=True)
    action = Column(String(200), nullable=False)
    resource_type = Column(String(100))
    resource_id = Column(String(255))
    details = Column(JSON)
    ip_address = Column(String(45))
    user_agent = Column(String(500))
    created_at = Column(DateTime, default=datetime.utcnow, nullable=False, index=True)